- .gitignore
- handlers/web_api.py
- models/attack_dict.json
- service/data_svc.py
- service/ml_svc.py
- service/rest_svc.py
- tram.py
- webapp/html/index.html
- webapp/theme/scripts/basics.js
Main fixes to prevent hanging queues and blank reports
> Multiple Tram fixes

- conf/config.yml
- database/dao.py
- database/tram_relation.py
- handlers/web_api.py
- service/data_svc.py
- service/rest_svc.py
- service/web_svc.py
- tram.py
- webapp/html/columns.html
- webapp/theme/scripts/basics.js
- Unique report titles
- Finer sentence splitting
- Added comments
> Tram Multiple Fixes pt.2

- handlers/web_api.py
- service/data_svc.py
- service/rest_svc.py
- service/web_svc.py
- tram.py
- webapp/html/columns.html
- webapp/html/index.html
- webapp/theme/scripts/basics.js
- Server side checks on REST requests
- URL checking
- Response header 'Server' omitted in calls
- index.html tidy-up
> Pentest fixes

- conf/config.yml
- handlers/web_api.py
- service/data_svc.py
- service/rest_svc.py
- tram.py
- webapp/JS Dependencies.md
- webapp/html/base.html
- webapp/html/columns.html
- webapp/html/index.html
- webapp/theme/scripts/basics.js
- webapp/theme/style/style.css
- Tidy up and documentation of JS imports
- Allowed slashes in report titles
- Improved display of sub techniques
> Js dependencies

- NOTICE.txt
- conf/config.yml
- conf/schema.sql
- database/dao.py
- database/tram_relation.py
- handlers/web_api.py
- models/attack_dict_json_notice.txt
- requirements.txt
- service/data_svc.py
- service/ml_svc.py
- service/reg_svc.py
- service/rest_svc.py
- service/web_svc.py
- tram.py
- webapp/html/about.html
- webapp/html/base.html
- webapp/html/columns.html
- webapp/html/index.html
- webapp/theme/scripts/basics.js
- webapp/theme/style/style.css
In accordance with TRAM's license terms, this PR adds NOTICEs on modified files. 
PR also includes a small db change for default parameters
> Added license info

- webapp/html/about.html
- webapp/html/base.html
- webapp/html/columns.html
- webapp/html/index.html
- webapp/theme/scripts/basics.js
- webapp/theme/style/style.css
I had incorrectly started indenting some JS, HTML & CSS files; this PR applies the same indenting across all these files (to revert the ones I changed and more).
[JS](https://google.github.io/styleguide/jsguide.html#formatting-block-indentation), [HTML & CSS](https://google.github.io/styleguide/htmlcssguide.html#Indentation) files are recommended to use 2 spaces for indentation.
> Applied uniform indentations

- conf/config.yml
- conf/schema.sql
- database/dao.py
- database/thread_db.py
- database/thread_postgresql.py
- database/thread_sqlite3.py
- handlers/web_api.py
- main.py
- service/data_svc.py
- service/ml_svc.py
- service/reg_svc.py
- service/rest_svc.py
- service/web_svc.py
- webapp/html/columns.html
- webapp/html/index.html
- webapp/theme/scripts/basics.js
Part 1 of the code changes to move away from SQLite
- Build db for DB server is now done as a different script option
- Boolean compatibility (not all DB engines use integers for booleans like SQLite)
- get() method abstracted
> Part 1: Add DB engine option

- conf/schema.sql
- database/dao.py
- database/thread_db.py
- database/thread_postgresql.py
- database/thread_sqlite3.py
- requirements.txt
- service/data_svc.py
- service/ml_svc.py
- service/reg_svc.py
- service/rest_svc.py
The rest of the DB changes to introduce PostgreSQL compatibility
- ThreadDB becomes an abstract class
- All SQL-generating code moved to ThreadDB
- All SQL queries updated
> Part 2: Add DB engine option

- conf/config.yml
- conf/schema.sql
- database/dao.py
- database/thread_db.py
- database/thread_postgresql.py
- database/thread_sqlite3.py
- handlers/web_api.py
- main.py
- requirements.txt
- service/data_svc.py
- service/ml_svc.py
- service/reg_svc.py
- service/rest_svc.py
- service/web_svc.py
- webapp/html/columns.html
- webapp/html/index.html
- webapp/theme/scripts/basics.js
A large PR covering the following smaller PRs (which have already been reviewed at time of merging):
Includes #15 and #17
> All db changes

- threadcomponents/handlers/web_api.py
- webapp/html/columns.html
- webapp/theme/style/style.css
Add help-text to token-protected reports to explain and advise on expired-session behaviour
> Added help-text to report page

- README.md
- main.py
- threadcomponents/handlers/web_api.py
- threadcomponents/service/data_svc.py
- threadcomponents/service/ml_svc.py
- threadcomponents/service/rest_svc.py
- webapp/html/about.html
- webapp/html/columns.html
- Update viewing completed reports
- README/About page content updates
> About Page and Completed Reports update

- .gitignore
- tests/test_reports.py
- tests/thread_app_test.py
- threadcomponents/service/rest_svc.py
- webapp/html/index.html
- webapp/html/submission-arachne-fields.html
- webapp/html/submission-form.html
- webapp/theme/scripts/basics.js
- webapp/theme/style/style.css
- Added helptext on submission tabs
- Empty-argument checks
- Link to CISA best-practices doc
> Homepage updates

- tests/test_reports.py
- tests/test_reports_dates.py
- tests/thread_app_test.py
- threadcomponents/database/thread_db.py
- threadcomponents/database/thread_postgresql.py
- threadcomponents/database/thread_sqlite3.py
- threadcomponents/handlers/web_api.py
- threadcomponents/service/data_svc.py
- threadcomponents/service/ml_svc.py
- threadcomponents/service/reg_svc.py
- threadcomponents/service/rest_svc.py
- webapp/html/columns.html
- webapp/theme/scripts/basics.js
- webapp/theme/style/style.css
Add start/end times to individual sentence-attack mappings
> Added times to sentence mappings

- threadcomponents/models/attack_dict.json
- threadcomponents/service/data_svc.py
- webapp/html/columns.html
- webapp/html/report-data.html
- Fixes issue when new categories are saved to DB but their full display name doesn't display in dropdown
- ATT&CK v12 changes to attack_dict.json
- Provided info on where to submit config (list) changes
- HTML tidy-up removing .btn-md class
> Config info & updates

- tests/test_reports.py
- tests/thread_app_test.py
- threadcomponents/handlers/web_api.py
- threadcomponents/service/data_svc.py
- webapp/html/columns.html
- webapp/theme/scripts/basics.js
- webapp/theme/style/style.css
On edit-report pages, a list shows how many attacks are awaiting review
> Outstanding Sentence-Attacks List

- README.md
- threadcomponents/handlers/web_api.py
- threadcomponents/service/rest_svc.py
- webapp/html/index.html
- Adds expiry date to all reports (regardless of status)
- README update for Shared vs Local
> Expiry on all queues

- threadcomponents/handlers/web_api.py
- threadcomponents/service/data_svc.py
On exporting report data, this PR includes IoCs in that export
> IoCs added to report-export

- threadcomponents/models/attack_dict.json
- json file update given the new release
https://attack.mitre.org/resources/updates/updates-april-2023/
> ATT&CK v13 update

- tests/test_iocs.py
- tests/test_reports.py
- tests/test_reports_dates.py
- tests/thread_app_test.py
- threadcomponents/service/rest_svc.py
- threadcomponents/service/web_svc.py
- webapp/html/columns.html
- webapp/theme/scripts/basics.js
- webapp/theme/style/style.css
- IoC updates
- rosettaStone updates
- Test suite: can now specify test-sentences
> Defanging iocs update

- tests/test_iocs.py
- threadcomponents/service/rest_svc.py
Handles when IoC IP addresses have special characters within the string
> IoCs IP Address special chars handling

- tests/test_iocs.py
- tests/thread_app_test.py
- threadcomponents/service/rest_svc.py
- threadcomponents/service/web_svc.py
- Moves some of the IP address cleaning for validation away from the refang() method
- Suppresses some loggers in the test suite
> Iocs URL vs IP cleaning

- tests/test_iocs.py
- tests/test_reports.py
- threadcomponents/handlers/web_api.py
- threadcomponents/service/rest_svc.py
- webapp/html/columns.html
- webapp/theme/scripts/basics.js
- webapp/theme/style/style.css
Previously enforced cleaned IoC strings now become suggestions
> Allow User to determine IoC text

- main.py
- threadcomponents/database/thread_postgresql.py
- threadcomponents/service/rest_svc.py
- threadcomponents/service/web_svc.py
- Allows a function to be passed on startup to pass db-connection details versus entering via inputs
- Some small tidy up for IoCs and newspaper-article checking
> Introduced db-connection function on startup

- .github/workflows/run-tests.yml
- main.py
- pyproject.toml
- tests/test_attack_data.py
- tests/test_db.py
- tests/test_reports.py
- tests/test_reports_dates.py
- tests/test_rest_svc.py
- tests/thread_app_test.py
- threadcomponents/database/dao.py
- threadcomponents/database/thread_db.py
- threadcomponents/handlers/web_api.py
- threadcomponents/service/data_svc.py
- threadcomponents/service/ml_svc.py
- threadcomponents/service/reg_svc.py
- threadcomponents/service/rest_svc.py
Before setting coding standards in #69, this PR adds a lint test with accompanying fixes.
This PR also includes some logging statements for report-analysis and our cron-jobs
> Add linter & logging statements

- threadcomponents/conf/schema.sql
- threadcomponents/service/rest_svc.py
Populate a table report_sentence_queue_progress for reports in the queue to monitor progress
> Add table report_sentence_queue_progress

- threadcomponents/service/rest_svc.py
Fix from issues caused by b466b33
> Fix: Queue jobs not being picked up

- main.py
- threadcomponents/conf/config.yml
- threadcomponents/handlers/web_api.py
- threadcomponents/service/rest_svc.py
- webapp/html/columns.html
- A temp solution for our performance issues - reduce the number of sentences passed to the ML models
> Add report-sentence limit

- tests/test_reports.py
- threadcomponents/service/rest_svc.py
- threadcomponents/service/web_svc.py
Following #76, large reports are still slowing Thread down. This PR uses the sentence limit during the analysis process to speed up the queue.
Pandas DataFrame/Series code is also tweaked.
> Sentence limit patch

- tests/test_iocs.py
- threadcomponents/handlers/web_api.py
- threadcomponents/service/rest_svc.py
- webapp/html/columns.html
- webapp/theme/scripts/basics.js
Adds suggest-& save IoC button to Thread
> Suggest-&-Save IoC

- threadcomponents/conf/schema.sql
- threadcomponents/service/rest_svc.py
- threadcomponents/service/web_svc.py
- Flag is changed from boolean to VARCHAR
- Tests remain with boolean values intentionally
> Updates to automatically_generated flag

- .gitmodules
- main.py
- tests/thread_app_test.py
- threadcomponents/database/thread_db.py
- threadcomponents/database/thread_postgresql.py
- threadcomponents/database/thread_sqlite3.py
- threadcomponents/handlers/web_api.py
- threadcomponents/reports/report_exporter.py
- threadcomponents/service/data_svc.py
- webapp/html/report-data.html
- WebAPI report-export request handlers moved into ReportExporter
- For PostgreQL queries, sentences are grouped by attack-data on PDF-export
- Table-headers repeat on page-break
- Spindle is named (previously rosettaStone)
- arachne-threat-intel/spindle#16
> Spindle & Report updates

- threadcomponents/service/web_svc.py
Filters out exact matches on sentences in reports.
> Reduced duplicate sentences in reports

- .github/workflows/run-tests.yml
- threadcomponents/service/data_svc.py
- webapp/html/about.html
- webapp/theme/scripts/basics.js
- Actioned SyntaxWarnings on startup
- Added Python 3.12 to run-tests.yml
- Updated using-Thread page
> Using-Thread, Spindle, + Python 3.12 updates

- .github/workflows/run-tests.yml
- README.md
- main.py
- tests/misc.py
- tests/test_attack_data.py
- tests/test_db.py
- tests/test_iocs.py
- tests/test_pages.py
- tests/test_reports.py
- tests/test_reports_dates.py
- tests/test_rest_svc.py
- tests/thread_app_test.py
- threadcomponents/database/dao.py
- threadcomponents/database/thread_db.py
- threadcomponents/database/thread_postgresql.py
- threadcomponents/database/thread_sqlite3.py
- threadcomponents/handlers/web_api.py
- threadcomponents/reports/report_exporter.py
- threadcomponents/service/data_svc.py
- threadcomponents/service/ml_svc.py
- threadcomponents/service/reg_svc.py
- threadcomponents/service/rest_svc.py
- threadcomponents/service/web_svc.py
Basically what it says on the tin... just thought it was a good idea to have consistent formatting across the code base.
> Code formatting with ruff

- threadcomponents/database/thread_postgresql.py
- threadcomponents/handlers/web_api.py
- threadcomponents/service/rest_svc.py
- webapp/theme/scripts/basics.js
This basically replicates the `reject_attack` functionality except it will remove all `true_negatives`** and `false_positives`. Plus it doesn't have the logic to add `false_positives` like the `reject_attack` does.
** I'm not actually sure that `true_negatives` ever get populated, but best to clean the table for the sentence regardless.
> Adding ignore button and functionality

- threadcomponents/service/data_svc.py
- Fixes a bug where ignored-attacks are flagged as awaiting confirmation
- Fixes a bug where sentence-flags on edit-page are out of order
> Updates to awaiting-confirmation-sentences on report-edit page

- threadcomponents/service/data_svc.py
This can then be used for training data for external systems.
> Send through true_positive, false_positive, false_negative info

- .mise.toml
- main.py
- tests/thread_app_test.py
- threadcomponents/handlers/web_api.py
- threadcomponents/repositories/report_repo.py
- threadcomponents/service/attack_data_svc.py
- threadcomponents/service/data_svc.py
- threadcomponents/service/ml_svc.py
- threadcomponents/service/reg_svc.py
- threadcomponents/service/rest_svc.py
- threadcomponents/service/token_svc.py
- threadcomponents/service/web_svc.py
The end goal to make it easier to call the `ml_svc` from other code without the need to bring in a thousand dependencies 😉
> Pulling stuff apart to decouple them

- README.md
- SUPPORT.md
- webapp/html/what-to-submit.html
Updates the links for Arachne's hosted version of Thread
> Link-update for Thread

- documentation/database.md
- requirements.txt
- threadcomponents/conf/config.yml
- threadcomponents/database/thread_db.py
- threadcomponents/database/thread_postgresql.py
- threadcomponents/service/data_svc.py
> psycopg2 to psycopg

- main.py
- threadcomponents/service/rest_svc.py
- threadcomponents/service/web_svc.py
This updates some of the error handling that occurs during a report-URL submission.
> Submission updates
